service: fargate-infra-ecr

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

resources:
  Resources:
    ecr:
      Type: AWS::ECR::Repository
      Properties: 
        ImageTagMutability: MUTABLE
        RepositoryName: "node-fargate"